apiVersion: v1
kind: Service
metadata:
  name: tiupserver
  labels:
    app: tiupserver
spec:
  ports:
    - protocol: TCP
      nodePort: 31989
      port: 8989
      targetPort: 8989
  type: NodePort
  selector:
    app: tiupserver

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tiupserver
spec:
  serviceName: "tiupserver"
  replicas: 1
  selector:
    matchLabels:
      app: tiupserver
  template:
    metadata:
      labels:
        app: tiupserver
    spec:
      containers:
        - name: tiupserver
          image: hub.pingcap.net/py/tiupserver:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: mirror
              mountPath: /home/tiupserver/mirror
            - name: keys
              mountPath: /home/tiupserver/keys
            - name: private
              mountPath: /home/tiupserver/mirror/private
      volumes:
        - name: keys
          secret:
            secretName: tiup-secret
        - name: private
          secret:
            secretName: tiup-private
  volumeClaimTemplates:
    - metadata:
        name: mirror
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-storage"
        resources:
          requests:
            storage: 50Gi
